stages:
  - test
  - build
  - deploy

backend test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  only:
    - merge_requests
  variables:
    SOLUTION_FILE: "./src/IdentityServer.sln"
  cache:
    key: "build_dependency_dotnet"
    paths:
      - nuget/
  before_script:
    - "dotnet restore $SOLUTION_FILE"
  script:
    - dotnet build $SOLUTION_FILE --configuration Release
    - echo !!!Build finished
    - dotnet test $SOLUTION_FILE

docker build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/identityserver:$CI_PIPELINE_IID
  before_script:
    - "cd ./src"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - "cd ."
  script:
    - docker-compose up -d
  only:
    - master
  when: manual