version: "3.4"

networks:
  isfa-network:
    driver: bridge

services:
  database.identity:
    container_name: isfa-database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: identity
      POSTGRES_ADMIN_PASSWORD: Str0ngPass!
    ports:
      - 5433:5432
    networks:
      - isfa-network

  identityserver:
    container_name: isfa-identityserver
    image: isfa/identityserver
    restart: always
    depends_on:
      - database.identity
      - elasticsearch
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_HTTPS_PORT: 5001
      ConnectionStrings:DefaultConnection: Host=database.identity;Database=identity;User Id=user;Password=Str0ngPass!
      ElasticSearch:ConnectionString: http://elasticsearch:9200
      MessageBroker:Host: "rabbitmq://admin:admin@rabbitmq:5672"
      IssuerUri: https://identityserver
    ports:
      - 5001:5001
    networks:
      - isfa-network
    volumes:
      - ~/.aspnet/https:/https:ro

  elasticsearch:
    container_name: isfa-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - isfa-network

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.9-management
    container_name: isfa-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - isfa-network

  kibana:
    container_name: isfa-kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - isfa-network
